require: rubocop-rails

AllCops:
  Exclude:
    - 'app/views/spree/api/**/*'
    - 'bin/*'
    - 'cache/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'spec/support/fixture_builder.rb'
    - 'tmp/**/*'
    - 'db/data/*'
    - 'db/data_schema.rb'
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'lib/aws-sdk.rb'
  TargetRubyVersion: 2.6

Metrics/LineLength:
  Exclude:
    - 'config/initializers/content_security_policy.rb'
    - 'config/initializers/backtrace_silencers.rb'
    - 'config/initializers/new_framework_defaults_6_0.rb'
    - 'config/environments/*.rb'
    - 'config/initializers/action_mailer.rb'
    - 'config/features.rb'
    - 'db/seeds.rb'
  Max: 100

Style/Documentation:
  Enabled: false

Layout/IndentFirstHashElement:
  EnforcedStyle: special_inside_parentheses
  SupportedStyles:
    - special_inside_parentheses
    - consistent
    - align_braces
  IndentationWidth: 4

Layout/IndentFirstArrayElement:
  EnforcedStyle: special_inside_parentheses
  SupportedStyles:
    - special_inside_parentheses
    - consistent
    - align_braces
  IndentationWidth: 4

Style/BlockComments:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
  SupportedStyles:
    - indented
    - indented_relative_to_receiver
  # By default, the indentation width from Style/IndentationWidth is used
  # But it can be overridden by setting this parameter
  IndentationWidth: 4

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - 'config/environments/*.rb'
    - 'config/routes.rb'
    - 'config/initializers/paperclip.rb'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'
# add this configuration to avoid raising error
# when using curly braces on select. ex: sort-select
# search index
Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent
